# Generated by Django 3.1 on 2020-08-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='')),
                ('file_path', models.FilePathField()),
                ('file_dateadded', models.DateField()),
            ],
        ),
    ]
