# Generated by Django 3.1 on 2020-08-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSVdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_dateadded',
        ),
        migrations.AddField(
            model_name='file',
            name='Date Added',
            field=models.DateField(auto_now=True, verbose_name='Date Added'),
        ),
    ]
