# Generated by Django 3.1 on 2020-08-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSVdata', '0004_auto_20200827_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='file_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='file_path',
            field=models.FileField(null=True, upload_to='%Y/%m/%d', verbose_name=''),
        ),
    ]
